1.optimize build option 2.update dockerfile

diff --git a/build b/build
--- a/build
+++ b/build
@@ -9,24 +9,24 @@ log() {
 
 usage() {
 	cat <<EOF
-Usage: [Rebuild=1] ./build <Target> <Version> [Path]
-Example: Rebuild=1 ./build mediatek_mt7623 19.07.2
+Usage: ./build -t Target -v Version -p Path -r
+example: ./build -t mediatek_mt7623 -v 19.07.2 -r
 
-Target: target_subtarget
-    example: mediatek_mt7623 x86_64 ...
+    -t Target:
+        target_subtarget
+        example: mediatek_mt7623 x86_64 ...
 
-Version:
-    17.01.1 - 17.01.7
-    18.06.0 - 18.06.9
-    19.07.0 - 19.07.10
-    21.02.0 - 21.02.7
-    22.03.0 - 22.03.5
-    23.05.0
-    example: 19.07.2 21.02.3
+    -v Version:
+        17.01.1 - 17.01.7
+        18.06.0 - 18.06.9
+        19.07.0 - 19.07.10
+        21.02.0 - 21.02.7
+        22.03.0 - 22.03.5
+        23.05.0
+        example: 19.07.2 21.02.3
 
-Path(optional): absolute path, default openwrt_subtarget_version
-
-Rebuild: means rebuild, when set 1, will rebuild
+    -p(optional): new directory(absolute path), default ./openwrt_subtarget_version
+    -r(optional): will rebuild, skip clone
 EOF
 	exit 1
 }
@@ -129,18 +129,38 @@ build() {
     docker_cmd ${cmd}
 }
 
-[ "$1" = "" ] || [ "$2" = "" ] && usage
-[ -e "./tmp" ] || mkdir tmp
+# initialize defaults
+Target=
+Version=
+Path=
+Rebuild=0
 
-Target=$1
-Version=$2
-Path=$3
+# parse options
+while [ -n "$1" ]; do
+	case "$1" in
+		-t) Target=$2; shift;;
+		-v) Version=$2; shift;;
+		-p) Path=$2; shift;;
+		-r) Rebuild=1;;
+		*)
+			echo "Invalid option: $1"
+            usage
+			exit 1
+		;;
+	esac
+	shift;
+done
+
+[ "$Target" = "" ] || [ "$Version" = "" ] && usage
+
+# initialize var
 container=${Target}_${Version}
 logfile=$(pwd)/tmp/build_${container}.log
 target=${Target%%_*}
 subtarget=${Target#*_}
 config_url=${target_url}${Version}/targets/${target}/${subtarget}/config.buildinfo
 [ "$Path" = "" ] && Path=$(pwd)/openwrt_${subtarget}_${Version//./_}
+[ -e "./tmp" ] || mkdir tmp
 
 init_docker
 check_input_valid
